### ISSUE TITLE
Crash when loading image in the carousel view on devices with API level <21

### ISSUE THREAD

**Issue by mkuennek** [HiP-App/HiP-Mobile#104]
When trying to run the app with the carousel view on devices with API level below 21, the app crashes as it fails to load the vector images for page 2 and 3.

Exception message:

"Android.Content.Res.Resources+NotFoundException: File res/drawable/ac_location.xml from drawable resource ID #0x7f02004b"

Location in AutoCarouselPageFragment:
image.SetBackgroundResource (Resource.Drawable.ac_location);

**Comment by NiWe90** [comment]
Maybe we can use this should work with API 14+ ?https://components.xamarin.com/gettingstarted/vectorcompat

or maybe this ?

https://www.nuget.org/packages/Softlion.XamSvg.Free/

**Comment by mkuennek** [comment]
I looked into this but couldn't manage to get it working. According to [this](https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u0prd0dhe) you should use "imageview.SetImageResource(Resource.drawable.somecevtor);". This solves the crash but the vector isn't displayed. We should have a look the the suggested libraries. Our current pipeline doesn't support Xamarin component restore though, so we have to wait for the new pipeline.
For now I'm gonna fix the crash but leave the actual fix for later, when we can use these libraries.
