### ISSUE TITLE
Bugreport: App not available in Play Store!

### ISSUE THREAD

**Issue by mkiehl** [HiP-App/HiP-Mobile#115]
Summary: The app is not available for download in the Google Play Store although it is November 2016.

Steps to reproduce the bug:
1. Go to https://play.google.com/store/
2. Input "Historisches Paderborn" into the search bar at the top
3. Click the magnifier icon

Expected result:
I get the HiP app as a search result and can download it to my phone

Actual result:
There is no link to the Historisches Paderborn app, see attached screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/4067920/19931631/832ba8e4-a10d-11e6-9e5e-05fff9664be6.png)

I hope you can fix this bug soon ;-)

**Comment by jonaskir** [comment]
I think @mkiehl should fix that :P

**Comment by smilicas** [comment]
Oooooh @mkiehl this is mean, pure version of mocking! :D :D :D

**Comment by NiWe90** [comment]
Will be fixed soon :P
