### ISSUE TITLE
Distance is not getting updated in the home screen

### ISSUE THREAD

**Issue by maltehol** [HiP-App/HiP-Mobile#116]
How to reproduce:
1. Open the app, GPS is off.
2. If you are on the Home-Screen turn on GPS.

The distance to location will not change, but if you rotate your phone it will.

![screenshot_20161102-190912](https://cloud.githubusercontent.com/assets/18170619/19941511/a86cea14-a130-11e6-88e3-1b03c8280e6c.png)

**Comment by weskampj** [comment]
i was not able to reproduce that error. i tried it with my phone(samsung) and with the simulator both worked for me
