### ISSUE TITLE
Hockeyapp update + Screen rotation

### ISSUE THREAD

**Issue by mkuennek** [HiP-App/HiP-Mobile#53]
If there is a new update, Hockeyapp shows a message in the main screen. If you click ignore and then rotate the screen, the message is shown again and again. This is annoying because if a user does not want to update for now, he always has to click ignore. The message should only be shown once(or at least in less frequent intervals)

**Comment by NiWe90** [comment]
done just have to add "ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize"
