### ISSUE TITLE
Timeslider is resetted after screen rotation

### ISSUE THREAD

**Issue by mkuennek** [HiP-App/HiP-Mobile#96]
1. Open app with timeslider page
2. Move the timeslider to the right
3. Rotate the screen
   => Timeslider is reset to the first image

**Comment by bastianbrinkmann** [comment]
Close because rotation is disabled or just change to enhancement?

**Comment by mkuennek** [comment]
We should close it as it is not relevant anymore(until we decide to support rotation again)
